#!/usr/bin/env groovy
// jenkins-shared-library/vars/sonarAnalysis.groovy
//
// Reusable SonarQube analysis step.
// Runs SonarQube analysis and waits for the Quality Gate result.
//
// Usage:
//   sonarAnalysis(
//     projectKey: 'payments-service',
//     language:   'java',              // 'java', 'javascript', 'python'
//     sonarToken: credentials('sonarqube-token')
//   )

def call(Map params = [:]) {
    def projectKey   = params.projectKey ?: error("sonarAnalysis: 'projectKey' is required")
    def language     = params.language   ?: 'java'
    def sonarToken   = params.sonarToken ?: error("sonarAnalysis: 'sonarToken' is required")
    def sonarHostUrl = params.sonarHostUrl ?: env.SONAR_HOST_URL ?: 'https://sonar.internal.bank.com'
    def sources      = params.sources    ?: 'src'
    def coverageReport = params.coverageReport ?: ''

    echo "📊 Starting SonarQube analysis for: ${projectKey}"
    echo "   Language: ${language} | Host: ${sonarHostUrl}"

    switch (language.toLowerCase()) {
        case 'java':
            runJavaSonar(projectKey, sonarToken, sonarHostUrl)
            break
        case 'javascript':
        case 'node':
            runJsSonar(projectKey, sonarToken, sonarHostUrl, sources, coverageReport)
            break
        case 'python':
            runPythonSonar(projectKey, sonarToken, sonarHostUrl, sources, coverageReport)
            break
        default:
            error "sonarAnalysis: unsupported language '${language}'. Use: java, javascript, python"
    }

    // Wait for Quality Gate — fails the pipeline if gate does not pass
    waitForSonarQualityGate(sonarToken, sonarHostUrl, projectKey)
}

private def runJavaSonar(String projectKey, String token, String hostUrl) {
    // Maven runs the analysis — results are sent to SonarQube
    // Coverage report is already generated by mvn verify (JaCoCo)
    sh """
        ./mvnw sonar:sonar \\
            -Dsonar.projectKey=${projectKey} \\
            -Dsonar.host.url=${hostUrl} \\
            -Dsonar.login=${token} \\
            -Dsonar.qualitygate.wait=false \\
            -B --no-transfer-progress
    """
}

private def runJsSonar(String projectKey, String token, String hostUrl,
                        String sources, String coverageReport) {
    def coverageFlag = coverageReport ? "-Dsonar.javascript.lcov.reportPaths=${coverageReport}" : ''
    sh """
        npx sonar-scanner \\
            -Dsonar.projectKey=${projectKey} \\
            -Dsonar.host.url=${hostUrl} \\
            -Dsonar.login=${token} \\
            -Dsonar.sources=${sources} \\
            -Dsonar.exclusions=node_modules/**,coverage/** \\
            ${coverageFlag}
    """
}

private def runPythonSonar(String projectKey, String token, String hostUrl,
                            String sources, String coverageReport) {
    def coverageFlag = coverageReport ? "-Dsonar.python.coverage.reportPaths=${coverageReport}" : ''
    sh """
        sonar-scanner \\
            -Dsonar.projectKey=${projectKey} \\
            -Dsonar.host.url=${hostUrl} \\
            -Dsonar.login=${token} \\
            -Dsonar.sources=${sources} \\
            -Dsonar.python.version=3.12 \\
            -Dsonar.exclusions=tests/**,**/__pycache__/**,**/migrations/** \\
            ${coverageFlag}
    """
}

private def waitForSonarQualityGate(String token, String hostUrl, String projectKey) {
    echo "⏳ Waiting for SonarQube Quality Gate result..."

    // Poll the SonarQube API for up to 5 minutes
    timeout(time: 5, unit: 'MINUTES') {
        waitUntil(initialRecurrencePeriod: 10000) {
            def response = sh(
                script: """
                    curl -sf -u ${token}: \\
                        "${hostUrl}/api/qualitygates/project_status?projectKey=${projectKey}" \\
                        | python3 -c "import sys,json; d=json.load(sys.stdin); print(d['projectStatus']['status'])"
                """,
                returnStdout: true
            ).trim()

            echo "Quality Gate status: ${response}"

            switch (response) {
                case 'OK':
                    echo "✅ Quality Gate PASSED for ${projectKey}"
                    return true
                case 'WARN':
                    echo "⚠️ Quality Gate WARNING for ${projectKey} — review issues"
                    return true
                case 'ERROR':
                    error """
                        ❌ Quality Gate FAILED for ${projectKey}
                        
                        Review issues at: ${hostUrl}/dashboard?id=${projectKey}
                        
                        Common causes:
                          - Code coverage below 80% threshold
                          - New Critical or Blocker issues introduced
                          - Security hotspots not reviewed
                    """
                case 'NONE':
                    echo "Quality Gate not yet computed — waiting..."
                    return false
                default:
                    echo "Unknown status: ${response} — retrying..."
                    return false
            }
        }
    }
}
