package com.globalpayments.paymentsservice.model.entity;

import com.globalpayments.paymentsservice.model.enums.Currency;
import com.globalpayments.paymentsservice.model.enums.PaymentStatus;
import com.globalpayments.paymentsservice.model.enums.PaymentType;
import jakarta.persistence.*;
import lombok.*;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

/**
 * Core Payment domain entity.
 *
 * Maps to the `payments` table (managed by Flyway migrations).
 * All monetary amounts are stored in minor units (pence/cents)
 * to avoid floating-point precision issues — a hard requirement
 * in financial systems.
 */
@Entity
@Table(
    name = "payments",
    indexes = {
        @Index(name = "idx_payments_reference",   columnList = "payment_reference"),
        @Index(name = "idx_payments_sender_acc",  columnList = "sender_account_id"),
        @Index(name = "idx_payments_receiver_acc",columnList = "receiver_account_id"),
        @Index(name = "idx_payments_status",      columnList = "status"),
        @Index(name = "idx_payments_created_at",  columnList = "created_at")
    }
)
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Payment {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(updatable = false, nullable = false)
    private UUID id;

    /**
     * Business-facing unique reference (e.g. PAY-2024-001234).
     * Generated by the service layer, not the DB.
     */
    @Column(name = "payment_reference", unique = true, nullable = false, length = 30)
    private String paymentReference;

    @Column(name = "sender_account_id", nullable = false, length = 34)
    private String senderAccountId;        // IBAN or account number

    @Column(name = "receiver_account_id", nullable = false, length = 34)
    private String receiverAccountId;

    @Column(name = "receiver_bank_code", nullable = false, length = 11)
    private String receiverBankCode;       // BIC/SWIFT

    /**
     * Amount in minor units (e.g., 1000 = £10.00).
     * NEVER store as float/double in financial systems.
     */
    @Column(name = "amount_minor_units", nullable = false)
    private Long amountMinorUnits;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 3)
    private Currency currency;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private PaymentStatus status;

    @Enumerated(EnumType.STRING)
    @Column(name = "payment_type", nullable = false, length = 20)
    private PaymentType paymentType;       // DOMESTIC, SEPA, SWIFT

    @Column(name = "description", length = 140)
    private String description;

    /**
     * External transaction reference from the clearing network
     * (populated on settlement).
     */
    @Column(name = "clearing_reference", length = 50)
    private String clearingReference;

    /** Optional idempotency key from the calling client. */
    @Column(name = "idempotency_key", unique = true, length = 64)
    private String idempotencyKey;

    /** Retry count for failed payments going through the retry queue. */
    @Column(name = "retry_count", nullable = false)
    @Builder.Default
    private Integer retryCount = 0;

    @Column(name = "failure_reason", length = 500)
    private String failureReason;

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /**
     * The authenticated user/service that initiated this payment.
     * Populated by Spring Security JPA auditing.
     */
    @CreatedBy
    @Column(name = "created_by", updatable = false, length = 100)
    private String createdBy;

    /** Optimistic locking — prevents lost updates in concurrent environments. */
    @Version
    private Long version;

    // ── Business Methods ───────────────────────────────────────────────────

    /**
     * Returns the amount as a human-readable BigDecimal.
     * E.g., 1050 minor units with 2 decimal places → 10.50
     */
    public BigDecimal getAmountAsDecimal() {
        return BigDecimal.valueOf(amountMinorUnits)
                         .movePointLeft(currency.getDecimalPlaces());
    }

    public boolean isFinalState() {
        return status == PaymentStatus.COMPLETED
            || status == PaymentStatus.FAILED
            || status == PaymentStatus.CANCELLED;
    }

    public boolean canRetry() {
        return status == PaymentStatus.FAILED && retryCount < 3;
    }
}
